### ISSUE TITLE
node stack remote vs local exection

### ISSUE THREAD

**Issue by copremesis** [copremesis/wafv2-ipset-serverless-experiments#1]
### Problem:

testing the `aws-node-scheduled-cron` stack 
has revealed and odd behavior when executing
`serverless invoke --function cronHandler`vs
`serverless invoke local --function cronHandler`

The same code works locally and not remotely. My first inclination is that it
is permission based. Since I'm now asking this scheduled Lambda to modify
another AWS resource. Ergo I augmented it execution policy. Another item
is to ensure environment variables are present in the exiting lambda using
_Cloudwatch_ logs and some tests. I would expect if there was a Timeout or
Permission issue there would be some sort of Error or Warning message.
So far 🦗 's.

`serverless logs -f cronHandler -t`

and enabling the cron 🍿 ... lets see if anything arrives

### Discussion

Here's a the code that performs differently.

``` javascript
const update_ipset = async (wafv2) => {
  console.log('BEGIN WAF UPDATE');
  await wafv2.getIPSet({
    Id: process.env.IPSET_ID,
    Name: process.env.NAME,
    Scope: 'REGIONAL',
  }, async (err, data) => {
    if (err) console.error(err, err.stack); // an error occurred
    else  {
      let lockToken = data.LockToken;
      //add address to the list
      let addresses = data.IPSet.Addresses.map(ip => ip);
      addresses.push('8.8.8.8/32');
      addresses.push('7.7.7.7/32');
      addresses.push('6.6.6.6/32');
      logJson(addresses);
      const params = {
        Addresses: addresses,
        Id: process.env.IPSET_ID,
        LockToken: lockToken,
        Name: process.env.NAME,
        Scope: 'REGIONAL',
        Description: 'scheduled sync'
      };
      await wafv2.updateIPSet(params, (err, data) => {
        if (err) console.error(err, err.stack); 
        else     console.log(data); 
      });
    }
  });
  console.log('END WAF UPDATE');
}
```
https://github.com/copremesis/wafv2-ipset-serverless-experiments/blob/main/aws-node-scheduled-cron/handler.js#L7

### Troubleshooting

- [x] IAM lambda policy has now been provided with
        ALL permissions on the ARN for this WAF::IPSet
- [x] Environment Variables are added to `serverless.yml`
- [ ] Would re-writing the solution above or decoupling some of it's nests help solve this puzzle?

**Comment by copremesis** [comment]
I've enabled the event scheduler and have it running every minute 
while running
`sls logs -f cronHandler -t`

it appears the plot thickens

```shell
UnknownEndpoint: Inaccessible host: `wafv2.us-west-2.amazonaws.com' at port `undefined'. This service may not be available in the `us-west-2' region.
    at Request.ENOTFOUND_ERROR (/var/task/node_modules/aws-sdk/lib/event_listeners.js:529:46)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:686:14)
    at error (/var/task/node_modules/aws-sdk/lib/event_listeners.js:361:22)
    at ClientRequest.<anonymous> (/var/task/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28) {
  code: 'UnknownEndpoint',
  region: 'us-west-2',
  hostname: 'wafv2.us-west-2.amazonaws.com',
  retryable: true,
  originalError: Error: write EPROTO
      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) {
    errno: -71,
    code: 'NetworkingError',
    syscall: 'write',
    region: 'us-west-2',
    hostname: 'wafv2.us-west-2.amazonaws.com',
    retryable: true,
    time: 2022-03-28T00:34:38.301Z
  },
  time: 2022-03-28T00:34:38.301Z
} UnknownEndpoint: Inaccessible host: `wafv2.us-west-2.amazonaws.com' at port `undefined'. This service may not be available in the `us-west-2' region.
    at Request.ENOTFOUND_ERROR (/var/task/node_modules/aws-sdk/lib/event_listeners.js:529:46)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:686:14)
    at error (/var/task/node_modules/aws-sdk/lib/event_listeners.js:361:22)
    at ClientRequest.<anonymous> (/var/task/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
2022-03-27 19:34:38.303	INFO	{
```

what's odd is we know this is working locally and is also working through the _aws cli_ 
so it's not exactly clear as to what is going on behind the scenes
